-- INSERT into burgers (burger_name,devoured,date) VALUES ('Ostrich Burger',FALSE,date);
-- INSERT into burgers (burger_name,devoured,date) VALUES ('Elk Burger',FALSE,date);
-- INSERT into burgers (burger_name,devoured,date) VALUES ('Brontasaurus Burger',FALSE,date);
-- INSERT into burgers (burger_name,devoured,date) VALUES ('Dill Burger',FALSE,date);
-- INSERT into burgers (burger_name,devoured,date) VALUES ('Rock Burger',TRUE,date);